#! /bin/sh

sxhkd &

bspc monitor -d 1 2 3 4

bspc config border_width         1
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color  \#181818
bspc config focused_border_color \#000000
bspc config urgent_border_color  \#000000
bspc config presel_border_color  \#000000

# Set monocle by default
for n in $(seq 1 4); do
    bspc desktop $n --layout monocle
done

feh --bg-scale ~/Pictures/FsIVsFQ.jpg
compton -b
polybar --reload top &